site_name: Mydocs

nav:
    - Home: index.md
    - API: API.md
    - About: about.md
    - Community: Community.md
    
theme:
    name: mkdocs
    custom_dir: custom_theme/
    footer:  custom_theme/custom_template.html


